import Header from '../Header';
import Head from 'next/head';

interface LayoutProps {
  children: React.ReactNode;
  className: string;
}

export default function GuestLayout(props: LayoutProps) {
  return (
    <>
      <Head>
        <title>Examine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={props.className}>{props.children}</main>
    </>
  );
}
